import './globals.css'
import { ReduxProvider } from './redux/provider'
import { Open_Sans } from 'next/font/google'

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={openSans.className}>
            <body>
                <ReduxProvider>{children}</ReduxProvider>
            </body>
        </html>
    )
}
